config/routes.rb
SampleApp::Application.routes.draw do
	get "users/new"
	
	match '/signup', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
	  @titre = "Accueil"
  end
  
  def contact
	  @titre = "Contact"
  end
  
  def about
	  @titre = "A propos"
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	  @titre = "Inscription"
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
	<ul>
		<li><%= link_to "A propos", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><a href="http://news.railstutorial.org/">News</a></li>
		<li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
  </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
		<% logo = image_tag("logo.png", :alt => "Application exemple", :class => "round") %>
		<%= link_to logo, root_path %>
		<nav class="round">
		<ul>
			<li><%= link_to "Accueil", root_path %></li>
			<li><%= link_to "Aide", help_path %></li>
			<li><%= link_to "Inscritption", "#" %></li>
		</ul>
		</nav>
	</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->   
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titre %></title>
	<%= csrf_meta_tag %>
   <%= render 'layouts/stylesheets' %>
  </head>
  <body>
	<div class="container">
		<%= render 'layouts/header' %>
	<section class="round">
	<%= yield %>
	</section>
	<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About US</h1>
<p>
  C'est la page de contact de l'Application Exemple du
  <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.

</p>>

app/views/pages/contact.html.erb
<h1>Contact App</h1>
<p>
  C'est la page de contact de l'Application Exemple du
  <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.

</p>

app/views/pages/help.html.erb
<h1>Help App</h1>
<p>
  C'est la page de help de l'Application Exemple du
  <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.

</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
  C'est la page d'accueil de l'Application Exemple du
  <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.
</p>

<%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>